# Generated by Django 4.0 on 2022-02-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
