# Generated by Django 4.0 on 2022-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer1',
        ),
    ]
