# Generated by Django 4.0 on 2022-02-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_customer_customer1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer1',
            new_name='Customer',
        ),
    ]
